---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redirector
  labels:
    app: redirector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redirector
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: redirector
        image: pingiun/redirector
        env:
        - name: LISTEN_ADDR
          value: 0.0.0.0:9376
        - name: RUST_LOG
          value: main=info
        ports:
        - containerPort: 9376
